name: wheel
description: this lib contains some common util.
version: 0.0.1
homepage: https://github.com/jiangxiaoqiang/wheel

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 4.0.0
  global_configuration: 2.0.0-nullsafety.1
  flutter_secure_storage: 5.0.2
  logger: 1.0.0
  hive: 2.0.4
  hive_flutter: 1.0.0
  timeago: 3.0.2
  in_app_purchase: 1.0.5
  device_info_plus: 3.2.1
  uuid: 3.0.5
  get: 4.5.0
  fluttertoast: 8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/cfg/
